# Generated by Django 4.2 on 2025-11-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='msg',
            field=models.TextField(),
        ),
    ]
