# Generated by Django 4.2 on 2025-11-12 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0003_alter_contact_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('register_at', models.DateTimeField(auto_now_add=True)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('address', models.TextField()),
                ('course', models.CharField(max_length=20)),
                ('timeslot', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Enrolled', 'Enrolled'), ('Reject', 'Reject')], max_length=20)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capp.signup')),
            ],
        ),
    ]
