# Generated by Django 4.2 on 2025-11-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0004_enroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_at', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('ingredient', models.TextField()),
                ('instruction', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('submit_by', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
