# Generated by Django 4.2 on 2025-11-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0005_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='file',
            field=models.FileField(upload_to='Receipedata'),
        ),
    ]
