# Generated by Django 4.2 on 2025-11-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0006_alter_notes_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='submit_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
